{"uuid": "b4c0800d-4256-46c0-acbf-0922d285381b", "children": ["4accd45c-9daa-42f2-8eb5-ac126f7f467e"], "befores": [{"name": "small_png_image", "status": "passed", "start": 1753968184721, "stop": 1753968184808}], "afters": [{"name": "small_png_image::0", "status": "broken", "statusDetails": {"message": "PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'small_7509.png'\n", "trace": "  File \"D:\\Anaconda3\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\工作记录\\项目说明\\api_test\\tests\\conftest.py\", line 37, in small_png_image\n    os.remove(img_path)\n"}, "start": 1753968185880, "stop": 1753968185888}], "start": 1753968184721, "stop": 1753968185888}