{"name": "test_user_auth[case28]", "status": "broken", "statusDetails": {"message": "KeyError: 'url'", "trace": "@pytest.fixture(scope=\"session\")\n    def auth_token():\n        \"\"\"获取管理员token\"\"\"\n        with allure.step(\"登录获取token\"):\n>           response = Request.send_request(\n                \"POST\", \"/auth/login\",\n                json={\"username\": \"admin1155\", \"password\": \"admin1155\"}\n            )\nE           KeyError: 'url'\n\ntests\\conftest.py:20: KeyError"}, "parameters": [{"name": "case", "value": "{'case_id': 'auth_029', 'name': '未登录状态上传头像', 'method': 'POST', 'url': '/auth/upload/avatar', 'headers': {'Content-Type': 'multipart/form-data'}, 'files': {'file': 'test_avatar.png'}, 'expected_code': 401, 'expected_success': False}"}], "start": 1753967267937, "stop": 1753967267937, "uuid": "35852d9a-bfb4-4464-b93c-07bc85c4309a", "historyId": "d0764555822da62de21d8a21be0e36d6", "testCaseId": "de18b51a986ebd96b4485f2c6341275e", "fullName": "tests.test_user_auth#test_user_auth", "labels": [{"name": "feature", "value": "用户认证模块"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_auth"}, {"name": "host", "value": "CYJ"}, {"name": "thread", "value": "24212-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_auth"}], "titlePath": ["tests", "test_user_auth.py"]}