{"name": "test_user_auth[case22]", "status": "broken", "statusDetails": {"message": "KeyError: 'url'", "trace": "@pytest.fixture(scope=\"session\")\n    def auth_token():\n        \"\"\"获取管理员token\"\"\"\n        with allure.step(\"登录获取token\"):\n>           response = Request.send_request(\n                \"POST\", \"/auth/login\",\n                json={\"username\": \"admin1155\", \"password\": \"admin1155\"}\n            )\nE           KeyError: 'url'\n\ntests\\conftest.py:20: KeyError"}, "parameters": [{"name": "case", "value": "{'case_id': 'auth_023', 'name': '新密码与旧密码相同', 'method': 'PUT', 'url': '/auth/userinfo', 'headers': {'Authorization': 'Bearer '}, 'json': {'oldPassword': 'admin1155', 'newPassword': 'admin1155', 'securityEmail': 'admin1155@example.com', 'verificationCode': '{verify_code}'}, 'expected_code': 400, 'expected_success': False, 'expected_message': '新密码不能与当前密码相同'}"}], "start": 1753966889887, "stop": 1753966889887, "uuid": "6aae27b5-7376-4544-b3c7-4840ebee349b", "historyId": "78c1f28a1eb1d7e1b021f39fa5697cd7", "testCaseId": "de18b51a986ebd96b4485f2c6341275e", "fullName": "tests.test_user_auth#test_user_auth", "labels": [{"name": "feature", "value": "用户认证模块"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_auth"}, {"name": "host", "value": "CYJ"}, {"name": "thread", "value": "10044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_auth"}], "titlePath": ["tests", "test_user_auth.py"]}