{"uuid": "ec5a2a89-425b-4d66-a7c6-6f83150e97b2", "children": ["fadd925a-6d8a-44f4-aed7-8740e90e05b3"], "befores": [{"name": "small_png_image", "status": "passed", "start": 1753969411174, "stop": 1753969411213}], "afters": [{"name": "small_png_image::0", "status": "broken", "statusDetails": {"message": "PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'small_8104.png'\n", "trace": "  File \"D:\\Anaconda3\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\工作记录\\项目说明\\api_test\\tests\\conftest.py\", line 36, in small_png_image\n    os.remove(img_path)\n"}, "start": 1753969412219, "stop": 1753969412222}], "start": 1753969411174, "stop": 1753969412223}