{"uuid": "02b0aab4-c4e2-44bd-83b4-e063bbd4ed7a", "children": ["b2dadc2a-6b51-4fe1-a32f-07b2440d2a3f"], "befores": [{"name": "small_png_image", "status": "passed", "start": 1753970306376, "stop": 1753970306490}], "afters": [{"name": "small_png_image::0", "status": "broken", "statusDetails": {"message": "PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'small_9388.png'\n", "trace": "  File \"D:\\Anaconda3\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\工作记录\\项目说明\\api_test\\tests\\conftest.py\", line 36, in small_png_image\n    os.remove(img_path)\n"}, "start": 1753970307504, "stop": 1753970307506}], "start": 1753970306376, "stop": 1753970307506}